// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7G-Cuk0Ly79VMQ9Jo8B6xjEmfGMEcPE',
    appId: '1:587711548592:web:7101058caf87d5dccaff75',
    messagingSenderId: '587711548592',
    projectId: 'hybrid-14b91',
    authDomain: 'hybrid-14b91.firebaseapp.com',
    storageBucket: 'hybrid-14b91.appspot.com',
    measurementId: 'G-48ELF3HL2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoyYEYyFM1HWijnUFcJg0jHK6JPG0Vdo',
    appId: '1:587711548592:android:f1ed5b1f3fb0d802caff75',
    messagingSenderId: '587711548592',
    projectId: 'hybrid-14b91',
    storageBucket: 'hybrid-14b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwRP8bDCaUWnW7kJ8UkMF8zH_Gx1HgnXg',
    appId: '1:587711548592:ios:eaba02676721285fcaff75',
    messagingSenderId: '587711548592',
    projectId: 'hybrid-14b91',
    storageBucket: 'hybrid-14b91.appspot.com',
    iosBundleId: 'com.meesalapavan.hybrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwRP8bDCaUWnW7kJ8UkMF8zH_Gx1HgnXg',
    appId: '1:587711548592:ios:95b53b632ef47a98caff75',
    messagingSenderId: '587711548592',
    projectId: 'hybrid-14b91',
    storageBucket: 'hybrid-14b91.appspot.com',
    iosBundleId: 'com.meesalapavan.hybrid.RunnerTests',
  );
}
